Hotfix/remove whitespace
UnUniFi/utils pull request #190
Opened 2022-01-18 13:30 UTC by taro04

[https://github.com/CauchyE/telescope/pull/265](https://github.com/CauchyE/telescope/pull/265)の横展開です。

以下のモジュールで秘密鍵を使用しており、空白文字の対応を実施しました。
●auction/auctions/**number**/price-bid
●cdp/cdps/create[createCDP]
●cdp/cdps/**accAddress**/clear[repayCDP]
●cdp/cdps/**accAddress**/deposit[depositCDP]
●cdp/cdps/**accAddress**/issue[drawCDP]
●cdp/cdps/**accAddress**/withdoraw[withdrawCDP]

ローカル環境で、空白文字が入っていてもTxSimulationが完了することを確認しました。

また、以前実施したレイアウトの修正（）で漏れている箇所があり、
合わせて修正しました。すみません。変化点は以下確認ください。
![20220118_pic2](https://user-images.githubusercontent.com/75844498/149945951-3454f504-5a8c-4b74-9956-573098b06e47.png)

加えて、cdpの[claer],[deposit],[issue],[withdraw]のページで
Gas settingのタイトルの大きさが異なっていることが気になったので
合わせて修正しました。

＜修正前＞
https://user-images.githubusercontent.com/75844498/149946385-75ebafb8-0eeb-434c-b811-679b4bbecec3.mp4

＜修正後＞
https://user-images.githubusercontent.com/75844498/149946439-a4ab085d-f28d-4cbe-a82e-58ef6b8da833.mp4

ご確認お願い致します。

2022-01-18 13:36 UTC, taro04 commented on projects/telescope-extension/src/app/models/cdps/cdp.infrastructure.service.ts
> -    const privKey = this.iKeyInfrastructure.getPrivKey(key.type, privateKey);
現在telescopeと同様の位置に実装していますが、
key.infrastructure.serviceの中に実装すれば変更点が一か所で済むのかなと思いました。

2022-01-19 02:17 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/models/cdps/cdp.infrastructure.service.ts
> -    const privKey = this.iKeyInfrastructure.getPrivKey(key.type, privateKey);
@taro04 
ありがとうございます。確かにこの点はご指摘の通りかもしれませんね。

@KimuraYu45z 
この点、いかがでしょうか？
key.infrastructure.serviceの中に、秘密鍵の文字列からホワイトスペースを除去する機能を移すのは「あり」でしょうか？

2022-01-19 02:30 UTC, KimuraYu45z commented on projects/telescope-extension/src/app/models/cdps/cdp.infrastructure.service.ts
> -    const privKey = this.iKeyInfrastructure.getPrivKey(key.type, privateKey);
うーむコードの簡潔さという点ではありなんですけどinfraの責任ではないですよねー

infraではないkey serviceに置くなら賛成です。

2022-01-19 05:51 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/models/cdps/cdp.infrastructure.service.ts
> -    const privKey = this.iKeyInfrastructure.getPrivKey(key.type, privateKey);
@KimuraYu45z 
ありがとうございます。それではkey.serviceに配置する形で進めようと思います。privateKeyだけでなく、publicKeyとmnemonicもついでにやってしまってよいかなと思っていますがもし問題あればフォローください。(mnemonicは途中のスペースは必要なので、先頭と終わりのスペースだけ消すような形(trimとかが楽？)に修正してもらう必要があると思っています。)

@taro04 
上記コメントの方針でお願いします。CauchyE/telescopeの方にもこの修正を逆輸入してあげてください。

2022-01-19 05:54 UTC, YasunoriMATSUOKA requested changes
@taro04 cc: @KimuraYu45z 
以下リンクのコメントの件、確認頂きありがとうございました。

https://github.com/UnUniFi/utils/pull/190#discussion_r787368685

コメントのやり取りを参考に、対応をお願いします。
(このプルリクの対応終わったら CauchyE/telescope の方も修正お願いします。)

2022-01-19 13:44 UTC, taro04 commented
・実装をKeyServiceに移しました。
・auction,cdpでkeyinfraserviceを直接触っていたのでkeyService経由に変更しました。

デバックはローカル環境で、以下のページで空白文字が入っていてもTxSimulationが完了することを確認しました。
●auction/auctions/number/price-bid
●cdp/cdps/accAddress/clear[repayCDP]
●cdp/cdps/accAddress/deposit[depositCDP]
●cdp/cdps/accAddress/issue[drawCDP]
●cdp/cdps/accAddress/withdoraw[withdrawCDP]
（publicKeyとmnemonicもprivatekeyと同様に修正していますがデバックはtelescope側で行っています。）

ご確認お願い致します。

2022-01-20 09:30 UTC, YasunoriMATSUOKA commented
@taro04 
実装は問題なさそうに見えました。
デバッグ方法としては、 CauchyE/telescope の方で登録したアカウントを使えば、simulateだけでなくトランザクションの実行までローカルでデバッグ可能だと思うので、そこまでデバッグして確認してみてもらえると助かります。
パブリックテストネットでデバッグのためにトランザクションを実際に投げても問題無いので、そこまで確認して頂いた上で、問題無ければApproveさせてもらおうと思います。確認お願いします。

2022-01-20 12:16 UTC, taro04 commented
以下の通りトランザクションの実行確認しました。
（アカウントのページでトランザクション一覧出るの便利ですね。）

[price-bid](http://a.test.ununifi.cauchye.net/txs/D0A2AE428BAE6B994A32B8B7217A749B4F9CA3094DA4DEA4C7D9E8EE78FC81EC)
[Deposit](http://a.test.ununifi.cauchye.net/txs/BFFA0860CCAEAEB5C4D115756B4A76F7431BD94324F5630681A570B5C432559C)
[Withdraw](http://a.test.ununifi.cauchye.net/txs/1EDE9B23AD4AC1D60EDE5D2F21329AC68F24529833AAA3F1DBFC71ED23A76E68)
[Draw](http://a.test.ununifi.cauchye.net/txs/07085BC5CA1CE8991CD40041DBAF8349B6EC52F4ADB6677C7F1DD76573CD3C86)
[Clear](http://a.test.ununifi.cauchye.net/txs/C3D267E78D8E5E1E4B046972701FAACB311489DD0A51CAB857AF1AD06A7D4E71)

（なお、Createはjpuが足りず（？）実行できませんでした。）
ご確認お願い致します。

2022-01-21 07:23 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/131279)

@taro04 cc: @KimuraYu45z 
こちらの環境ではcreateも実行できたので問題ないと判断します。
http://a.test.ununifi.cauchye.net/txs/25FF7F8345B884648EBF538C947D396F011034EE3E6EF442DBBBD429382AD97F

おそらく、つのださんの環境では、対象アカウントにて、既にcdpをcreate済だったのではないでしょうか？(あるいは担保に入れたubtcの時価が、発行しようとしていたjpuの額面の1.5倍を下回っていたとかでしょうか？)

仕様的に、cdpのポジションを既に持っている場合、cdpを新たに別途createすることはできないようで、担保の加減、cdpのポジション量の加減という形で、ポジションの変動を表現する仕様になっているようなので、その点承知しておいてください。

2022-01-21 07:24 UTC, merged